In [4]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_pickle('../data/raw/SESNA_INPUTS_JakeJune20.pkl')
df

,ID,ra,dec,VALID_FNU_J,VALID_FNU_H,VALID_FNU_KS,VALID_FNU_3_6,VALID_FNU_4_5,VALID_FNU_5_8,VALID_FNU_8_0,...,FNU_3_6,SIGMA_FNU_3_6,FNU_4_5,SIGMA_FNU_4_5,FNU_5_8,SIGMA_FNU_5_8,FNU_8_0,SIGMA_FNU_8_0,FNU_24,SIGMA_FNU_24
0,J033021.04+582049.3,52.587681,58.347026,1,1,1,3,3,3,3,...,0.118,1.000,0.060,1.0,0.330,1.000,0.422,1.0,1.183,0.095
1,J032839.47+582051.7,52.164451,58.347690,1,1,1,3,3,3,3,...,0.133,1.000,0.097,1.0,0.226,1.000,0.311,1.0,1.355,0.141
2,J032940.82+582053.3,52.420074,58.348142,1,1,1,3,3,3,3,...,0.115,1.000,0.138,1.0,0.318,1.000,0.415,1.0,2.079,0.083
3,J032539.46+582059.2,51.414429,58.349764,1,1,1,3,3,3,3,...,0.071,1.000,0.220,1.0,0.349,1.000,0.379,1.0,13.738,0.297
4,J032908.84+582101.5,52.286843,58.350428,1,1,1,3,3,3,3,...,0.218,1.000,0.051,1.0,0.385,1.000,0.292,1.0,0.537,0.089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5645585,J222752.84+642612.9,336.970156,64.436914,1,1,1,1,3,1,3,...,14.998,0.202,0.083,1.0,6.823,0.101,1.140,1.0,1.381,1.000
5645586,J222759.59+642615.4,336.998298,64.437601,1,1,1,1,3,3,3,...,0.792,0.017,0.143,1.0,0.483,1.000,1.183,1.0,8.310,1.000
5645587,J222755.73+642636.7,336.982188,64.443518,1,1,3,1,3,3,3,...,0.178,0.007,0.129,1.0,0.211,1.000,1.096,1.0,10.234,1.000
5645588,J222753.71+642650.8,336.973803,64.447441,1,1,1,1,3,3,3,...,0.159,0.008,0.143,1.0,0.331,1.000,1.183,1.0,10.234,1.000
5645589,J222717.73+642652.7,336.823862,64.447959,1,1,1,3,3,3,3,...,0.166,1.000,0.134,1.0,0.215,1.000,0.442,1.0,0.878,0.156

In [3]:
np.sum(df['VALID_FNU_H'] == 1) / df.shape[0]

0.7316494821621832

In [4]:
%cat ../data/raw/data_ngc2264_20.txt

20                             100.20250   9.59936 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 3 3   0.000e+00   0.000e+00   0.000e+00   0.000e+00   1.505e-02   1.505e-03   1.039e-01   1.039e-02   4.707e-01   4.707e-02   9.703e+00   9.703e-01   3.341e+01   3.341e+00   7.543e+01   7.543e+00   1.604e+02   1.604e+01   2.194e+02   2.194e+01   3.057e+02   3.057e+01   4.060e+02   4.060e+01   5.055e+02   5.055e+01   6.670e+02   6.670e+01   9.523e+02   9.523e+01   1.172e+03   1.172e+02   1.239e+03   1.239e+02   1.331e+03   1.331e+02   1.290e+03   1.290e+02   0.000e+00   0.000e+00   3.294e+03   1.000e+00   2.900e+02   1.000e+00

In [2]:
def make_source_ascii(table):
    src = ''
    for i in range(len(table)):
        src += " ".join(str(thingbob) for thingbob in table.iloc[i].to_list()) + '\n'
    return src

In [55]:
source_ascii = make_source_ascii(df)
print(source_ascii[0:20])
print(source_ascii[100:120])
print(source_ascii[200:220])

J033021.04+582049.3
 1.0 0.06 1.0 0.33 1
0.345 0.043 0.489 0.

In [56]:
print(len(source_ascii))

816111388

In [57]:
with open('../data/raw/sesna_sources_formatted','w') as savefile:
    savefile.write(source_ascii)

In [11]:
df_norm = pd.read_pickle('../data/raw/SESNA_INPUTS_JakeJune20.pkl')
df_norm

,ID,ra,dec,VALID_FNU_J,VALID_FNU_H,VALID_FNU_KS,VALID_FNU_3_6,VALID_FNU_4_5,VALID_FNU_5_8,VALID_FNU_8_0,...,FNU_3_6,SIGMA_FNU_3_6,FNU_4_5,SIGMA_FNU_4_5,FNU_5_8,SIGMA_FNU_5_8,FNU_8_0,SIGMA_FNU_8_0,FNU_24,SIGMA_FNU_24
0,J033021.04+582049.3,52.587681,58.347026,1,1,1,3,3,3,3,...,0.118,1.000,0.060,1.0,0.330,1.000,0.422,1.0,1.183,0.095
1,J032839.47+582051.7,52.164451,58.347690,1,1,1,3,3,3,3,...,0.133,1.000,0.097,1.0,0.226,1.000,0.311,1.0,1.355,0.141
2,J032940.82+582053.3,52.420074,58.348142,1,1,1,3,3,3,3,...,0.115,1.000,0.138,1.0,0.318,1.000,0.415,1.0,2.079,0.083
3,J032539.46+582059.2,51.414429,58.349764,1,1,1,3,3,3,3,...,0.071,1.000,0.220,1.0,0.349,1.000,0.379,1.0,13.738,0.297
4,J032908.84+582101.5,52.286843,58.350428,1,1,1,3,3,3,3,...,0.218,1.000,0.051,1.0,0.385,1.000,0.292,1.0,0.537,0.089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5645585,J222752.84+642612.9,336.970156,64.436914,1,1,1,1,3,1,3,...,14.998,0.202,0.083,1.0,6.823,0.101,1.140,1.0,1.381,1.000
5645586,J222759.59+642615.4,336.998298,64.437601,1,1,1,1,3,3,3,...,0.792,0.017,0.143,1.0,0.483,1.000,1.183,1.0,8.310,1.000
5645587,J222755.73+642636.7,336.982188,64.443518,1,1,3,1,3,3,3,...,0.178,0.007,0.129,1.0,0.211,1.000,1.096,1.0,10.234,1.000
5645588,J222753.71+642650.8,336.973803,64.447441,1,1,1,1,3,3,3,...,0.159,0.008,0.143,1.0,0.331,1.000,1.183,1.0,10.234,1.000
5645589,J222717.73+642652.7,336.823862,64.447959,1,1,1,3,3,3,3,...,0.166,1.000,0.134,1.0,0.215,1.000,0.442,1.0,0.878,0.156

In [6]:
df_norm.columns

Index(['ID', 'ra', 'dec', 'VALID_FNU_J', 'VALID_FNU_H', 'VALID_FNU_KS',
       'VALID_FNU_3_6', 'VALID_FNU_4_5', 'VALID_FNU_5_8', 'VALID_FNU_8_0',
       'VALID_FNU_24', 'FNU_J', 'SIGMA_FNU_J', 'FNU_H', 'SIGMA_FNU_H',
       'FNU_KS', 'SIGMA_FNU_KS', 'FNU_3_6', 'SIGMA_FNU_3_6', 'FNU_4_5',
       'SIGMA_FNU_4_5', 'FNU_5_8', 'SIGMA_FNU_5_8', 'FNU_8_0', 'SIGMA_FNU_8_0',
       'FNU_24', 'SIGMA_FNU_24'],
      dtype='object')

In [14]:
# Normalization of SESNA on H band, still need to propagate to errors
norm_factor = df_norm['FNU_H']
df_norm.iloc[:,11:26:2] = df_norm.iloc[:,11:26:2].div(norm_factor,axis=0)
#df_norm.iloc[:,11:26:2]
sigB = df_norm['SIGMA_FNU_H'].div(norm_factor,axis=0)**2
sigA = df_norm.iloc[:,12:27:2]
sigA
#sigma = df_norm.iloc[:,11:26:2] * np.sqrt((df_norm.iloc[:,12:27:2].div(df_norm.iloc[:,11:26:2],axis=0))**2 + (df_norm['SIGMA_FNU_H'].div(norm_factor,axis=0))**2)
#sigma

#with open('../data/raw/SESNA_normalized','w') as output:
#    output.write(make_source_ascii(df_norm))

,SIGMA_FNU_J,SIGMA_FNU_H,SIGMA_FNU_KS,SIGMA_FNU_3_6,SIGMA_FNU_4_5,SIGMA_FNU_5_8,SIGMA_FNU_8_0,SIGMA_FNU_24
0,0.331,0.629,0.848,1.000,1.0,1.000,1.0,0.095
1,0.043,0.058,0.060,1.000,1.0,1.000,1.0,0.141
2,0.043,0.069,0.071,1.000,1.0,1.000,1.0,0.083
3,5.662,13.296,11.639,1.000,1.0,1.000,1.0,0.297
4,1.385,0.946,0.778,1.000,1.0,1.000,1.0,0.089
...,...,...,...,...,...,...,...,...
5645585,0.740,0.900,0.599,0.202,1.0,0.101,1.0,1.000
5645586,0.198,0.163,0.142,0.017,1.0,1.000,1.0,1.000
5645587,0.053,0.063,1.000,0.007,1.0,1.000,1.0,1.000
5645588,0.048,0.063,0.075,0.008,1.0,1.000,1.0,1.000
5645589,0.046,0.064,0.087,1.000,1.0,1.000,1.0,0.156